export const SET_HAS_HOUSE_FILTER = "SET_HAS_HOUSE_FILTER"
export const SET_HAS_FENCED_YARD_FILTER = "SET_HAS_FENCED_YARD_FILTER"
export const SET_DOESNT_OWN_DOG_FILTER = "SET_DOESNT_OWN_DOG_FILTER"
export const SET_DOESNT_OWN_CAT_FILTER = "SET_DOESNT_OWN_CAT_FILTER"